### ISSUE TITLE
NameError: name 'load_model_as_safetensor' is not defined

### ISSUE THREAD

**Issue by EKI-INDRADI** [Gowtham58/Video_Backgroud_Remover_Green_Screen#2]
Traceback (most recent call last):
  File "V:\_GREEN_SCREEN_REMOVER\Video-Background-Remover-Green-Screen\app.py", line 16, in <module>
    bgrm = BriaRMBG.from_pretrained("briaai/RMBG-1.4")
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\greenscreen_20240511\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\greenscreen_20240511\lib\site-packages\huggingface_hub\hub_mixin.py", line 511, in from_pretrained
    instance = cls._from_pretrained(
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\greenscreen_20240511\lib\site-packages\huggingface_hub\hub_mixin.py", line 745, in _from_pretrained
    return cls._load_as_safetensor(model, model_file, map_location, strict)
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\greenscreen_20240511\lib\site-packages\huggingface_hub\hub_mixin.py", line 769, in _load_as_safetensor
    load_model_as_safetensor(model, model_file, strict=strict)  # type: ignore [arg-type]
NameError: name 'load_model_as_safetensor' is not defined

**Comment by EKI-INDRADI** [comment]
line  16 :

bgrm = BriaRMBG.from_pretrained("briaai/RMBG-1.4")

**Comment by Gowtham58** [comment]
@EKI-INDRADI were you connected to the internet while running the program?

**Comment by EKI-INDRADI** [comment]
yups , need disable internet ?

**Comment by EKI-INDRADI** [comment]
other code https://github.com/Scripting-Wizard/Background-remover running well, but can only remove background pictures

**Comment by Gowtham58** [comment]
Try Replacing this
```
bgrm = BriaRMBG.from_pretrained("briaai/RMBG-1.4")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#device = "cpu"
bgrm.to(device)
```
with this
```
from huggingface_hub import hf_hub_download
bgrm = BriaRMBG()
model_path = hf_hub_download("briaai/RMBG-1.4", 'model.pth')
if torch.cuda.is_available():
    bgrm.load_state_dict(torch.load(model_path))
    net = bgrm.cuda()
else:
    bgrm.load_state_dict(torch.load(model_path, map_location="cpu"))
net.eval()
```

**Comment by EKI-INDRADI** [comment]
```sh
from huggingface_hub import hf_hub_download
bgrm = BriaRMBG()
model_path = hf_hub_download("briaai/RMBG-1.4", 'model.pth')
if torch.cuda.is_available():
    bgrm.load_state_dict(torch.load(model_path))
    net = bgrm.cuda()
else:
    bgrm.load_state_dict(torch.load(model_path, map_location="cpu"))
net.eval()
```

still error

OS : Windows 10 x64

```sh
Traceback (most recent call last):
  File "V:\_GREEN_SCREEN_REMOVER\Video-Background-Remover-Green-Screen\app.py", line 32, in <module>
    net.eval()
NameError: name 'net' is not defined. Did you mean: 'next'?
```

**Comment by EKI-INDRADI** [comment]
SOLVED

replace with 

```sh
from huggingface_hub import hf_hub_download
# Load the RMBG model
bgrm = BriaRMBG()
model_path = hf_hub_download("briaai/RMBG-1.4", 'model.pth')
if torch.cuda.is_available():
    print("CUDA is available. Using GPU.")
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    bgrm.load_state_dict(torch.load(model_path))
    bgrm = bgrm.cuda()
else:
    print("CUDA is not available. Using CPU.")
    bgrm.load_state_dict(torch.load(model_path, map_location="cpu"))
bgrm.eval()
```


but only work with cpu only, for fix enable cuda
```sh
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118
```
